OC.L10N.register(
    "auto_groups",
    {
    "Group \"%1$s\" is used in the Auto Groups App and cannot be deleted." : "Úsáidtear grúpa \"%1$s\" san aip Auto Groups agus ní féidir é a scriosadh.",
    "Auto Groups" : "Grúpaí Gluaisteán",
    "Automatically adds all users to one or multiple specified groups." : "Cuireann sé gach úsáideoir go huathoibríoch le grúpa sonraithe amháin nó níos mó.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Settings > Administration > Additional settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login\n\nNote that this app prevents group deletions for groups referenced as Auto Groups or Override Groups.\n\n## Comparison to similar Apps\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): The \"Everyone Group\" app adds a virtual Group Backend, always returning all users. In contrast, \"Auto Groups\" operates on \"real\" groups in your normal Group Backend. Additionally, it is possible to specify Override Groups which will prevent users from being added to the Auto Group(s).\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): \"Auto Groups\" is actually a modernized and maintaned fork of \"Default Group\", which seems to be abandoned since NC12 or so. In terms of functionality, they are almost identical." : "Cuir úsáideoirí leis na Grúpaí Uathoibríocha sonraithe go huathoibríoch, seachas na húsáideoirí sin a bhaineann le ceann de na Grúpaí Sáraithe sonraithe.\n\nDe rogha air sin, is féidir an sannadh grúpa a spreagadh ar gach logáil isteach rathúil, rud atá úsáideach do chúlchríocha úsáideoirí seachtracha.\n\n## Cumraíocht\n\n- Téigh go \"Socruithe > Riarachán > Socruithe breise\"\n- Cumraigh na Grúpaí Uathoibríocha\n- Más gá, cumraigh na Grúpaí Sáraithe (m.sh., do Chuntais Seirbhíse)\n- De rogha air sin, cumasaigh an Hook Logála Isteach, a fhorfheidhmeoidh ballraíocht ghrúpa cheart ar gach logáil isteach rathúil\n\nTabhair faoi deara go gcoisceann an aip seo scriosadh grúpa do ghrúpaí dá dtagraítear mar Ghrúpaí Uathoibríocha nó Grúpaí Sáraithe.\n\n## Comparáid le hAipeanna comhchosúla\n\n* [Grúpa Gach Duine](https://apps.nextcloud.com/apps/group_everyone): Cuireann an aip \"Grúpa Gach Duine\" Cúlchríoch Grúpa fíorúil leis, ag filleadh gach úsáideoir i gcónaí. I gcodarsnacht leis sin, oibríonn \"Grúpaí Uathoibríocha\" ar ghrúpaí \"fíor\" i do Chúlchríoch Grúpa gnáth. Ina theannta sin, is féidir Grúpaí Sáraithe a shonrú a chuirfidh cosc ​​​​ar úsáideoirí a chur leis an nGrúpa(í) Uathoibríocha.\n* [Grúpa Réamhshocraithe](https://apps.nextcloud.com/apps/defaultgroup): Is forc nuachóirithe agus cothabháilte de \"Grúpa Réamhshocraithe\" é \"Auto Groups\" i ndáiríre, a bhfuil an chuma air go bhfuil sé tréigthe ó NC12 nó mar sin. Ó thaobh feidhmiúlachta de, tá siad beagnach mar a chéile.",
    "Automatically add all users to these groups." : "Cuir gach úsáideoir leis na grúpaí seo go huathoibríoch.",
    "Override Groups:" : "Sáraigh Grúpaí:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "Baintear úsáideoirí atá ina mbaill de cheann amháin ar a laghad de na grúpaí seo de na grúpaí uathoibríocha. Tá sé seo amhlaidh freisin má chuirtear an t-úsáideoir le ceann de na grúpaí seo tar éis an chruthaithe, i.e., seiceáiltear ballraíocht sna grúpaí sáraithe tar éis gach modhnú grúpa.",
    "Set Auto Group membership on user creation." : "Socraigh ballraíocht Auto Group ar chruthú úsáideoirí.",
    "If checked, Auto Group membership will be enforced on user creation." : "Má dhéantar é a sheiceáil, cuirfear ballraíocht Auto Group i bhfeidhm ar chruthú úsáideoirí.",
    "Check Auto Group membership on modification of a user's groups." : "Seiceáil ballraíocht Auto Group ar mhodhnú grúpaí úsáideoirí.",
    "If checked, Auto Group membership will be re-enforced for a user account every time it is added to or removed from a group." : "Má dhéantar é a sheiceáil, déanfar ballraíocht Auto Group a ath-fhorghníomhú do chuntas úsáideora gach uair a chuirtear le grúpa é nó nuair a bhaintear é de.",
    "Check for correct Auto Group membership on every login." : "Seiceáil an bhfuil ballraíocht cheart ag Auto Group ar gach logáil isteach.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "Cumasaigh an socrú seo chun ballraíocht cheart Auto Group a chur i bhfeidhm ar gach logáil isteach rathúil. Tá sé seo úsáideach mura gcruthaítear úsáideoirí in Nextcloud (m.sh., le haiséil úsáideoirí seachtracha) nó chun ballraíocht ghrúpa cheart a fhorfheidhmiú do gach úsáideoir nuair a athraítear na Grúpaí Auto / Override Groups."
},
"nplurals=5; plural=(n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4);");
