OC.L10N.register(
    "auto_groups",
    {
    "Group \"%1$s\" is used in the Auto Groups App and cannot be deleted." : "Grupė „%1$s“ naudojama automatinių grupių programoje ir jos negalima ištrinti.",
    "Auto Groups" : "Automatinės grupės",
    "Automatically adds all users to one or multiple specified groups." : "Automatiškai prideda visus vartotojus į vieną ar kelias nurodytas grupes.",
    "Automatically add users to the specified Auto Groups, except those users belonging to one of the specified Override Groups. \nOptionally, the group assignment can be triggered on every successful login, which is useful for external user backends.\n\n## Configuration\n\n- Go to \"Settings > Administration > Additional settings\"\n- Configure the Auto Groups\n- If required, configure the Override Groups (e.g., for Service Accounts)\n- Optionally, enable the Login Hook, which will enforce correct group membership on every successful login\n\nNote that this app prevents group deletions for groups referenced as Auto Groups or Override Groups.\n\n## Comparison to similar Apps\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): The \"Everyone Group\" app adds a virtual Group Backend, always returning all users. In contrast, \"Auto Groups\" operates on \"real\" groups in your normal Group Backend. Additionally, it is possible to specify Override Groups which will prevent users from being added to the Auto Group(s).\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): \"Auto Groups\" is actually a modernized and maintaned fork of \"Default Group\", which seems to be abandoned since NC12 or so. In terms of functionality, they are almost identical." : "Vartotojus automatiškai priskirkite nurodytoms automatinėms grupėms, išskyrus tuos, kurie priklauso vienai iš nurodytų nepaisymo grupių. \nPasirinkus šią parinktį, grupės priskyrimas gali būti inicijuojamas po kiekvieno sėkmingo prisijungimo, o tai yra naudinga dirbant su išorinėmis vartotojų duomenų bazėmis.\n\n## Konfigūracija\n\n- Eikite į „Nustatymai > Administravimas > Papildomi nustatymai“\n- Konfigūruokite automatines grupes\n- Jei reikia, konfigūruokite nepaisymo grupes (pvz., paslaugų paskyroms)\n- Jei norite, įjunkite prisijungimo gaudyklę, kuri užtikrins teisingą priklausomybę grupėms po kiekvieno sėkmingo prisijungimo.\n\nAtkreipkite dėmesį, kad ši programa neleidžia ištrinti grupių, nurodytų kaip automatinės grupės arba nepaisymo grupės.\n\n## Palyginimas su panašiomis programėlėmis\n\n* [Everyone Group](https://apps.nextcloud.com/apps/group_everyone): Programėlė „Everyone Group“ prideda virtualų grupių posistemę, visada grąžinančiąį visus vartotojus. Tuo tarpu „Automatinės Groupės“ veikia su „tikromis“ grupėmis jūsų įprastoje grupių posistemėje. Be to, galima nurodyti nepaisymo grupes, kurios neleis vartotojams būti priskirtiems prie automatinių grupių.\n* [Default Group](https://apps.nextcloud.com/apps/defaultgroup): „Automatinės Groupės“ iš tiesų yra modernizuota ir prižiūrima „Numatytosios grupės“ atšaka, kuri, atrodo, buvo apleista maždaug nuo NC12 versijos. Funkcionalumo požiūriu jos yra beveik identiškos.",
    "Automatically add all users to these groups." : "Automatiškai pridėti visus naudotojus į šias grupes.",
    "Override Groups:" : "Nepaisymo grupės:",
    "Users which are member of at least one of these groups are removed from the auto groups. This is also the case if the user is added to one of these groups after creation, i.e., membership in the override groups is checked after each group modification." : "Vartotojai, kurie yra bent vienos iš šių grupių nariai, pašalinami iš automatiškai sudaramų grupių. Tas pats pasakytina ir apie atvejus, kai vartotojas pridedamas prie vienos iš šių grupių po sukūrimo, t. y. narystė nepaisymo grupėse tikrinama po kiekvieno grupės pakeitimo.",
    "Set Auto Group membership on user creation." : "Nustatykite automatinę grupės narystę kuriant vartotoją.",
    "If checked, Auto Group membership will be enforced on user creation." : "Jei pažymėta, automatiškai sukuriant vartotoją bus nustatomas grupės narystė.",
    "Check Auto Group membership on modification of a user's groups." : "Patikrinkite automatinę grupės narystę modifikuojant vartotojo grupes.",
    "If checked, Auto Group membership will be re-enforced for a user account every time it is added to or removed from a group." : "Jei pažymėta, automatinė grupės narystė bus iš naujo taikoma vartotojo paskyrai kiekvieną kartą, kai ji bus pridėta prie grupės arba pašalinta iš jos.",
    "Check for correct Auto Group membership on every login." : "Kiekvieną kartą prisijungdami patikrinkite, ar teisingai priskirta „Automatinės Groupės“ narystė.",
    "Enable this setting to enforce proper Auto Group membership on every successful login. This is useful if either users are not created in Nextcloud (e.g., with external user backends) or to enforce correct group membership for all users when the Auto Groups / Override Groups have changed." : "Įjunkite šį nustatymą, kad kiekvieno sėkmingo prisijungimo metu būtų užtikrinta tinkama Automatinė grupės narystė. Tai naudinga, jei vartotojai nėra sukurti „Nextcloud“ (pvz., naudojant išorinius vartotojų serverius) arba norint užtikrinti teisingą visų vartotojų grupės narystę, kai pasikeičia automatinės grupės / nepaisymo grupės."
},
"nplurals=4; plural=(n % 10 == 1 && (n % 100 > 19 || n % 100 < 11) ? 0 : (n % 10 >= 2 && n % 10 <=9) && (n % 100 > 19 || n % 100 < 11) ? 1 : n % 1 != 0 ? 2: 3);");
