name: Build and Submit to App Store

on:
  pull_request: # TODO REMOVE
  release:
    types:
      - published

env:
  APP_NAME: auto_groups

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: ${{ env.APP_NAME }}

      - name: Clean up files
        run: cd ${{ env.APP_NAME }} && rm -rf .git composer.json screenshots tests .github .tx && cd ..

      - name: Define Archive Name
        run: echo ::set-env name=ARCHIVE_NAME::${{ env.APP_NAME }}.tar.gz # TODO ADD GITHUB_REF

      - name: Create Archive
        run: tar -zcvf ${{ env.ARCHIVE_NAME }} ${{ env.APP_NAME }}/
    
      - name: Create Archive Signature
        run: echo ::set-env name=SIGNATURE::$(echo "${{ secrets.AUTO_GROUPS_SIGNING_KEY }}" | openssl dgst -sha512 -sign /dev/stdin  ${{ env.ARCHIVE_NAME }}  | openssl base64)

      - name: Output Signature
        run: echo $SIGNATURE

      - name: List files
        run: ls -la