name: Build and Submit to App Store

on:
  pull_request: # TODO REMOVE
  release:
    types:
      - published

env:
  APP_NAME: auto_groups

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: ${{ env.APP_NAME }}

      - name: Clean up files
        run: cd ${{ env.APP_NAME }} && rm -rf .git composer.json screenshots tests .github .tx && cd ..

      - name: Define Archive Name
        uses: allenevans/set-env@v1.0.0
        with:
          ARCHIVE_NAME: ${{ env.APP_NAME }}.tar.gz # TODO ADD GITHUB_REF

      - name: Create Archive
        run: tar -zcvf ${{ env.ARCHIVE_NAME }} ${{ env.APP_NAME }}/
    
      - name: Create Archive Signature
        run: echo ${{}} | openssl dgst -sha512 -sign /dev/stdin  ${{ env.ARCHIVE_NAME }}  | openssl base64