name: Build and Submit to App Store

on:
  pull_request: # TODO REMOVE
  release:
    types:
      - published

env:
  APP_NAME: auto_groups

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: ${{ env.APP_NAME }}

      - name: Clean up files
        run: cd ${{ env.APP_NAME }} && rm -rf .git composer.json screenshots tests .github .tx && cd ..

      - name: Create Archive
        # run: tar -zcvf ${{ env.APP_NAME }}_$GITHUB_REF.tar.gz ${{ env.APP_NAME }}/
        run: tar -zcvf ${{ env.APP_NAME }}.tar.gz ${{ env.APP_NAME }}/ # TODO REMOVE
    
      - name: List files
        run: ls -la